.TH MU ADD 1 "July 2012" "User Manuals"

.SH NAME

mu add\-  add one or more messages to the database

.SH SYNOPSIS

.B mu add <file> [<files>]

.SH DESCRIPTION

\fBmu add\fR is the command to add specific message files to the
database. Each file must be specified with an absolute path.

.SH OPTIONS

\fBmu add\fR does not have its own options, but the general options for
determining the location of the database (\fI--muhome\fR) are available. See
\fBmu-index(1)\fR for more information.

.SH RETURN VALUE

\fBmu add\fR returns 0 upon success; in general, the following error codes are
returned:

.nf
| code | meaning                           |
|------+-----------------------------------|
|    0 | ok                                |
|    1 | general error                     |
|    5 | some database update error        |
.fi

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
.BR mu-index(1)
.BR mu-remove(1)
