.TH MU-BOOKMARKS 5 "May 2011" "User Manuals"

.SH NAME 

bookmarks \- file with bookmarks (shortcuts) for mu search expressions

.SH DESCRIPTION

Bookmarks are named shortcuts for search queries. They allow using a
convenient name for often-used queries. The bookmarks are also visible as
shortcuts in the mu experimental user interfaces, \fImug\fR and \fImug2\fR.

\fBmu\fR supports bookmarks stored in a file called \fBbookmarks\fR in the mu
home directory (typically, this would be \fI~/.mu/bookmarks\fR).

The bookmarks file is a typical key=value \fB.ini\fR-file, which is best shown
by means of an example:

.nf
    [mu]
    inbox=maildir:/inbox                  # inbox
    oldhat=maildir:/archive subject:hat   # archived with subject containing 'hat'
.fi

The \fB[mu]\fR group header is required.

For practical uses of bookmarks, see mu-find(1).

.SH LOCATION

The bookmarks file is read from \fI<muhome>/bookmarks\fR. Typically, this
would be \fI~/.mu/bookmarks\fR, but this can be influenced using the
\fB\-\-muhome\fR parameter for mu-find(1) and mug(1).

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

mu(1) mu-find(1)
