.TH MU CLEANUP 1 "October 2010" "User Manuals"

.SH NAME 

mu cleanup \- clean up the mu database

.SH SYNOPSIS

.B mu cleanup [options]

.SH DESCRIPTION

\fBmu cleanup\fR is the \fBmu\fR sub-command for removing messages from the mu
database that are no longer present in the file system.

The \fBcleanup\fR command removes messages for which no corresponding file can
be found, from the database. Note that this is done automatically when running
\fBmu index\fR (unless \fB\-\-nocleanup\fR was specified).

\fBmu cleanup\fR does not remove messages that are outside the currently
specified Maildir as long as they still exist.

.SH BUGS

Please report bugs if you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR maildir(5)
.BR mu-index(1)
.BR mu(1)
