.TH MU CLEANUP 1 "April 2011" "User Manuals"

.SH NAME 

mu cleanup \- clean up the mu database

.SH SYNOPSIS

.B mu cleanup [options]

.SH DESCRIPTION

\fBcleanup\fR removes messages from the database for which no corresponding
file can be found in the file system. This is done automatically when running
\fBmu index\fR (unless \fB\-\-nocleanup\fR was specified), but \fBmu cleanup\fR
can be used to do the cleanup explicitely.

\fBmu cleanup\fR does not remove messages that are outside the currently
specified Maildir, as long as they still exist. The command only takes global
options, which are described in the \fBmu (1)\fR man page.

.SH RETURN VALUE

\fBmu cleanup\fR return 0 upon successful completion. Anything else leads to a
non-zero return value, for example:

.sh
| code | meaning                        |
|------+--------------------------------|
|    0 | ok                             |
|    1 | general error                  |
|    4 | database is corrupted          |
.si

.SH BUGS

Please report bugs if you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR maildir(5) mu-index(1) mu(1)
