.TH MU EXTRACT 1 "January 2011" "User Manuals"

.SH NAME 

mu extract\- display and save message parts (attachments)

.SH SYNOPSIS

.B mu extract [options] <file> [<parts-to-save>]

.SH DESCRIPTION

\fBmu extact\fR is the \fBmu\fR sub-command for extracting MIME-parts (e.g.,
attachments) from mail messages. It works on message files, and does not
require the message to be indexed.

For attachments, the file name specified in the mail message is used (if
any). If there is no name, or when saving other mime-parts, a name is used
derived from the message-id of the message.

.SH OPTIONS

.TP
\fB\-a\fR, \fB\-\-save\-attachments\fR
save all MIME-parts that look like attachments.

.TP
\fB\-\-save\-all\fR
save all non-multipart MIME-parts.

.TP
\fB\-\-parts\fR=<parts>
only consider the following numbered parts
(comma-separated list).The numbers for the parts can be seen from running
\fBmu extract\fR without any options but only the message file.

.TP
\fB\-\-target\-dir\fR=<dir>
save the parts in the target directory rather than
the current working directory.

.TP
\fB\-\-overwrite\fR
overwrite existing files with the same name; by default overwriting is not
allowed.

.TP
\fB\-\-play\fR
Try to 'play' (open) the attachment with the corresponding
application. Depends on the \fBxdg-open\fR utility.


.SH BUGS
Please report bugs if you find them:

.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1) xdg-open(1)
