.TH MU EXTRACT 1 "September 2010" "User Manuals"

.SH NAME 

mu extract\- display and save message parts (attachments)

.SH SYNOPSIS

.B mu extract [options] <file> [<parts-to-save>]

.SH DESCRIPTION

\fBmu extact\fR is the \fBmu\fR sub-command for extracting MIME-parts (e.g.,
attachments) from mail messages. It works on message files, and does not require the
message to be indexed.

For attachments, the name specified in the message is used; when saving
mime-parts, a name is used, derived from the message-id of the message. Thus,

.SH OPTIONS

.TP
\fB\-a\fR, \fB\-\-save\-attachments\fR
save all MIME-parts that look like attachments.

\fB\-\-save\-all-parts\fR
save all non-multipart MIME-parts.

\fB\-\-target\-dir\fR=<dir>
save the parts in the target directory rather than the current one.

\fB\-\-overwrite\fR
overwrite existing files with the same name.

.SH BUGS

Please report bugs if you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
