.TH MU FLAGS 1 "April 2022" "User Manuals"

.SH NAME

mu flags\-  list all message flags

.SH SYNOPSIS

.B mu flags [options]

.SH DESCRIPTION

\fBmu flags\fR is the \fBmu\fR command for showing a table of message flags and their properties, which is useful for devising queries.

.SH OPTIONS

Inherits common options from
.BR mu(1)

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu (1)
