.TH MU FIELDS 1 "April 2022" "User Manuals"

.SH NAME

mu fields\-  list all message fields

.SH SYNOPSIS

.B mu fields [options]

.SH DESCRIPTION

\fBmu fields\fR is the \fBmu\fR command for showing a table of message fields
and their properties.

.SH OPTIONS

Inherits common options from
.BR mu(1)

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu (1)
