.TH MU HELP 1 "July 2012" "User Manuals"

.SH NAME

\fBmu help\fR is a \fBmu\fR command that gives help information about mu
commands.

.SH SYNOPSIS

.B mu help <command>

.SH DESCRIPTION

\fBmu help\fR provides help information about mu commands.

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu-index(1)
.BR mu-find(1)
.BR mu-cfind(1)
.BR mu-mkdir(1)
.BR mu-view(1)
.BR mu-extract(1)
.BR mu-easy(1)
.BR mu-bookmarks(5)
