.TH MU-INFO 1 "May 2022" "User Manuals"

.SH NAME

mu info \- show information about the mu database

.SH SYNOPSIS

.B mu info [options]

.SH DESCRIPTION

\fBmu info\fR is the \fBmu\fR command for getting information about the mu
database. Note that while running (e.g. \fBmu4e\fR), some of the information
may be slightly delayed due to database caching.

.SH OPTIONS

Note, some of the general options are described in the \fBmu(1)\fR man-page and
not here, as they apply to multiple mu commands.

.TP
\fB\-\-muhome\fR
use an alternative directory to store and read the database, write the logs,
etc. By default, \fBmu\fR uses XDG Base Directory Specification (e.g. on Linux
this defaults to \fI~/.cache/mu\fR, \fI~/.config/mu\fR). Earlier versions of
\fBmu\fR defaulted to \fI~/.mu\fR, which now requires \fI\-\-muhome=~/.mu\fR.

.SH RETURN VALUE

\fBmu init\fR returns 0 upon successful completion, or a non-zero exit code if
there was some error.

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR maildir (5),
.BR mu (1),
.BR mu-index (1)
