.TH MU MKDIR 1 "July 2012" "User Manuals"

.SH NAME

mu mkdir\-  create a new Maildir

.SH SYNOPSIS

.B mu mkdir [options] <dir> [<dirs>]

.SH DESCRIPTION

\fBmu mkdir\fR is the \fBmu\fR command for creating Maildirs. It does
\fBnot\fR use the mu database. With the \fBmkdir\fR command, you can create
new Maildirs with permissions 0755. For example,

.nf
   mu mkdir tom dick harry
.fi

creates three maildirs, \fItom\fR, \fIdick\fR and \fIharry\fR.

If creation fails for any reason, \fBno\fR attempt is made to remove any parts
that were created. This is for safety reasons.

.SH OPTIONS

.TP
\fB\-\-mode\fR=<mode>
set the file access mode for the new maildir(s) as in \fBchmod(1)\fR.

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR maildir(5)
.BR mu(1)
.BR chmod(1)
