.TH MU REMOVE 1 "July 2012" "User Manuals"

.SH NAME

\fBmu remove\fR is the \fBmu\fR command to remove messages from the database.

.SH SYNOPSIS

.B mu remove [options] <file> [<files>]

.SH DESCRIPTION

\fBmu remove\fR removes specific messages from the database, each of them
specified by their filename. The files do not have to exist in the file
system.

.SH OPTIONS

\fBmu remove\fR does not have its own options, but the general options for
determining the location of the database (\fI--muhome\fR) are available. See
\fBmu-index(1)\fR for more information.

.SH RETURN VALUE

\fBmu remove\fR returns 0 upon success; in general, the following error codes are
returned:

.nf
| code | meaning                           |
|------+-----------------------------------|
|    0 | ok                                |
|    1 | general error                     |
|    5 | some database update error        |
.fi

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
.BR mu-index(1)
.BR mu-add(1)
