.TH MU VERIFY 1 "October 2012" "User Manuals"

.SH NAME

mu stats\- run statistic on the mu database

.SH SYNOPSIS

.B mu stats [options] [--stat=<statistic>] [<query>]

.SH DESCRIPTION

\fBmu stats\fR is the \fBmu\fR command to get statistics from the \fBmu\fR
database. The statistics are implement in the Guile programming language, and
thus only work if your \fBmu\fR is built with support for Guile. In addition,
you need to have \fBgnuplot\fR installed.

\fBmu stats\fR supports a number of different statistics; running \fBmu
stats\fR without any options, lists the available statistics.

.SH OPTIONS

.TP
\fB\-\-stat=\fR\fI<statistic>\fR
show the results for the given statistic

\fB\-\-textonly\fR
show the statistics in text-only format, even if the environment is
capable of graphics.

\fB\-\-muhome\fR
causes \fBmu\fR to use an alternative directory to
store and read its database and logs. By default, \fI~/.mu\fR is used.

.SH RETURN VALUE

\fBmu stats\fR returns 0 when all went well, and returns some non-zero error
code when this is not the case.

.SH BUGS

Please report bugs if you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
