.TH MU SCRIPT 1 "June 2013" "User Manuals"

.SH NAME

mu script\- show the available mu scripts, and run them.

.SH SYNOPSIS

.B mu script [options] [<pattern>]

.B mu <script-name> [<script-options>]

.SH DESCRIPTION

\fBmu script\fR is the \fBmu\fR command to list available \fBmu\fR scripts.
The scripts are to be implemented in the Guile programming language, and
therefore only work if your \fBmu\fR is built with support for Guile. In
addition, many scripts require you to have \fBgnuplot\fR installed.

Without any parameters, \fBmu script\fR lists the available scripts. If you
provide a pattern (a regular expression), only the scripts whose name or
one-line description match this pattern are listed. See the examples below.

\fBmu\fR ships with a number of scripts.

.SH OPTIONS

.TP
\fB\-\-verbose\fR,\fB\-v\fR
when listing the available scripts, show the long descriptions.

\fB\-\-\fR
all options on the right side of the \fB\-\-\fR are passed to the script.

.SH EXAMPLES

List all available scripts (one-line descriptions):
.nf
  $ mu script
.fi

List all available scripts matching \fImonth\fR (long descriptions):
.nf
  $ mu script -v month
.fi

Run the \fImsgs-per-month\fR script for messages matching 'hello', and pass it
the \fI--textonly\fR parameter:
.nf
  $ mu msgs-per-month --query=hello --textonly
.fi

.SH RETURN VALUE

\fBmu script\fR returns 0 when all went well, and returns some non-zero error
code when this is not the case.

.SH FILES

You can make your own Scheme scripts accessible through \fBmu script\fR by
putting them in \fI<muhome>/scripts\fR (which is typically
\fI~/.mu/scripts\fR). It is a good idea to document the scripts by using some
special comments in the source code:
.nf
;; INFO: this is my script -- one-line description
;; INFO: (longer description)
;; INFO: --option1=<foo> (describe option1)
;; INFO: etc.
.fi

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
.BR guile(1)
