.TH MU-SERVER 1 "January 2020" "User Manuals"

.SH NAME

mu server \- the mu backend for the mu4e e-mail client

.SH SYNOPSIS

.B mu server [options]

.SH DESCRIPTION

\fBmu server\fR starts a simple shell in which one can query and manipulate the
mu database. The output uses s-expressions. \fBmu server\fR is not meant for use
by humans, except for debugging purposes. Instead, it is designed specifically
for the \fBmu4e\fR e-mail client.

In this man-page, we document the commands \fBmu server\fR accepts, as well as
their responses. In general, the commands sent to the server are s-expressions
of the form:

.nf
   (<command-name> :param1 value1 :param2 value2)
.fi

For example, to view a certain message, the command would be:

.nf
   (view :docid 12345)
.fi

Parameters can be sent in any order; they must be of the correct type though.
See \fBlib/utils/mu-sexp-parser.hh\fR and \fBlib/utils/mu-sexp-parser.cc\fR in
source-tree for the details.


.SH OUTPUT FORMAT

\fBmu server\fR accepts a number of commands, and delivers its results in
the form:

.nf
   \\376<length>\\377<s-expr>
.fi

\\376 (one byte 0xfe), followed by the length of the s-expression expressed as
an hexadecimal number, followed by another \\377 (one byte 0xff), followed by
the actual s-expression.

By prefixing the expression with its length, it can be processed more
efficiently. The \\376 and \\377 were chosen since they never occur in valid
UTF-8 (in which the s-expressions are encoded).

.sh COMMANDS


.SH AUTHOR
Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"
.BR mu (1)
