.TH MU-SERVER 1 "December 2011" "User Manuals"

.SH NAME

mu server \- the mu backend for the mm e-mail cleint

.SH DESCRIPTION

\fBmu server\fR starts a simple shell in which can manipulate the mu
database. The output of the commands is terms of symbolic expressions
(s-exps). \fBmu server\fR is not meant for use by humans; instead, it is
designed specifically for the \fBmm\fR e-mail client.

.SH OUTPUT FORMAT

\fBmu server\fR accepts a number of commands, and delivers its results in
the form:

 \\376<length>\\376s-expr

\\367 (that is, the character with ascii value 254, \\376 in octac notation),
followed by the length of the s-expression, followed by another \\376,
followed by the actual s-expression.

By prefixing the expression with length, it can be processed more
efficiently. The \\376 (254) was choses since it is a value that will never
occur in valid UTF-8 (in which the s-expressions are encoded).

.SH COMMAND AND RESPONSE




.SH AUTHOR
Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"
.BR mu(1)
