.TH MU VIEW 1 "May 2011" "User Manuals"

.SH NAME 

mu view\- display an e-mail message file

.SH SYNOPSIS

.B mu view [options] <file> [<files>]

.SH DESCRIPTION

\fBview\fR is the \fBmu\fR sub-command for displaying an e-mail message
file. It works on message files and does \fInot\fR require the message to be
indexed in the database.

The command shows some common headers (From:, To:, Cc:, Bcc:, Subject: and
Date:), the list of attachments and the plain-text body of the message (if
any).

.SH OPTIONS

.TP
\fB\-\-summary\fR
instead of displaying the full message, output a summary based upon the first
lines of the message.

\fB\-\-separate\fR
add an ascii \\014 (0x0c, or \fIform-feed\fR) between messages when displaying
multiple messages.


.SH BUGS

Please report bugs if you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
.BR mu-index(1)
