.TH MU VIEW 1 "June 2013" "User Manuals"

.SH NAME

mu view\- display an e-mail message file

.SH SYNOPSIS

.B mu view [options] <file> [<files>]

.SH DESCRIPTION

\fBmu view\fR is the \fBmu\fR command for displaying e-mail message files. It
works on message files and does \fInot\fR require the message to be indexed in
the database.

The command shows some common headers (From:, To:, Cc:, Bcc:, Subject: and
Date:), the list of attachments and the plain-text body of the message (if
any).

.SH OPTIONS

.TP
\fB\-\-summary-len\fR=\fI<number>\fR
instead of displaying the full message, output a summary based upon the first
\fI<number>\fR lines of the message.

.TP
\fB\-\-terminate\fR
terminate messages with \\f (\fIform-feed\fR) characters when displaying
them. This is useful when you want to further process them.

.TP
\fB\-\-decrypt\fR
attempt to decrypt encrypted message bodies. This is only possible if \fBmu\fR
was built with crypto-support. Users are strongly recommended to use
\fBgpg-agent\fR; however, if needed, \fBmu\fR will request the user password
from the console.

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
.BR mu-index(1)
.BR gpg(1)
.BR gpg-agent(1)
