.TH MU VIEW 1 "August 2010" "User Manuals"

.SH NAME 

mu view\- display an e-mail message file

.SH SYNOPSIS

.B mu view <file> [<files>]

.SH DESCRIPTION

\fBmu view\fR is the \fBmu\fR sub-command for displaying an e-mail message
file. It works on files, and does not require the message to be indexed before
using
.BR mu-index(1)
\.

Currently, the command shows some common headers (From:, To:, Cc:, Subject:
and Date:) and the plain-text body of the message.

.SH BUGS

There probably are some; please report bugs when you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1)
