.TH MU VERIFY 1 "April 2022" "User Manuals"

.SH NAME

mu verify\- verify message signatures and display information about them

.SH SYNOPSIS

.B mu verify [options] <msgfile>

.SH DESCRIPTION

\fBmu verify\fR is the \fBmu\fR command for verifying message signatures (such
as PGP/GPG signatures) and displaying information about them. The sub-command
works on message files, and does not require the message to be indexed in the
database.

.SH OPTIONS

.TP
\fB\-r\fR, \fB\-\-auto\-retrieve\fR
attempt to find keys online (see the \fBauto-key-retrieve\fR option in the
\fBgnupg(1)\fR documentation).

.SH EXAMPLES

To display aggregated (one-line) information about the verification status in a
message:
.nf
   $ mu verify msgfile
.fi

To display information about all the signatures:
.nf
   $ mu verify --verbose msgfile
.fi

If you only want to use the exit code, you can use:
.nf
   $ mu verify --quiet msgfile
.fi
which does not give any output unless there is an error.

.SH RETURN VALUE

\fBmu verify\fR returns 0 when all signatures could be verified to be good, and
returns some non-zero error code when this is not the case.

When there are no signatures, returns 0 as well.

.nf
| code | meaning                        |
|------+--------------------------------|
|    0 | ok                             |
|    1 | some non-verified signature(s) |
.fi

.SH BUGS

Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu (1)
