.TH MU 1 "August 2010" "User Manuals"

.SH NAME 

mu \- index and search e-mail messages stored in Maildirs

.SH SYNOPSIS

.B mu index [options]

.B mu cleanup [options]

.B mu find [options] <search expression>

.B mu view <file> [<files>]

.B mu mkdir [options] <dir> [<dirs>]

.B mu extract [options] <file> [<parts>]

.B mu [options]

.SH DESCRIPTION

\fBmu\fR is a set of tools for dealing with e-mail messages in Maildirs. 

Its main function is enable searching of e-mail messages. It does so by
scanning a Maildir directory tree and analyzing the e-mail messages found. The
results of this analysis are stored in a database, which can then be queried.

In addition to indexing and searching, \fBmu\fR also offers functionality for
viewing messages and creating maildirs.

\fBmu\fR can be used from the command line, or can be integrated with e-mail
clients. Note: the various sub-commands have their own manpages.

.SH COMMANDS

\fBmu\fR offers the following commands:

.TP
\fBindex\fR
for indexing (analyzing) the contents of your Maildirs, and storing the
information in a database. See
.BR mu-index(1)
\.

.TP
\fBcleanup\fR
for removing messages from the database for which there is no longer a
corresponding message file in the file system. See
.BR mu-cleanup(1)
\.

.TP
\fBfind\fR for finding messages in your database, using certain search
parameters. See
.BR mu-find(1)
\.

.TP
\fBview\fR
for displaying e-mail messages. See
.BR mu-view(1)
\.

.TP
\fBmkdir\fR
for creating Maildirs. See
.BR mu-mkdir(1)
\.


.TP
\fBextract\fR
for extract MIME-parts (such as attachments) from messages. See
.BR mu-extract(1)
\.

Subcommands \findex\fR, \ffind\fR and \cleanup\fR work with the database,
while the other ones work on invidual mail files. Hence, running \fview\fR,
\fBmkdir\fR and \fBextract\fR does not require the mu database.

.TP
The various commands are discussed in more detail in their own separate
man-pages; here the general options are discussed.

.SH GENERAL OPTIONS

\fBmu\fR offers a number of general options that apply to all commands,
including \fBmu\fR without any command.

.TP
\fB\-\-muhome\fR
causes \fBmu\fR to use an alternative directory to
store and read its database and logs. By default, \fI~/.mu\fR is used.

.TP
\fB\-d\fR, \fB\-\-debug\fR
makes \fBmu\fR generate extra debug information,
useful for debugging the program itself. By default, debug information goes to
the log file, \fI~/.mu/mu.log\fR. It can safely be deleted when \fBmu\fR is
not running. Note, with the debug option, the log file can grow rather
quickly. See the note on logging below.

.TP
\fB\-q\fR, \fB\-\-quiet\fR
causes \fBmu\fR not to output informational
messages and progress information to standard output, but only to the log
file. Error messages will still be sent to standard error. Note that \fBmu
index\fR is \fBmuch\fR faster with \fB\-\-quiet\fR, so it is recommended you
use this option when using \fBmu\fR from scripts etc.

.TP
\fB\-\-log-stderr\fR
causes \fBmu\fR not to output all log messages
to standard error, in addition to sending them to the log file.

.TP
\fB\-v\fR, \fB\-\-version\fR
outputs the \fBmu\fR-version and copyright
information.

.TP
\fB\-h\fR, \fB\-\-help\fR
list the various command line options, while
\fB\-\-help\-index\fR, \fB\-\-help\-find\fR and \fB\-\-help\-all\fR list only
the options for one command, or all of the commands.

.SH BUGS

There probably are some; please report bugs when you find them:
.BR http://code.google.com/p/mu0/issues/list

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu-index(1)

.BR mu-cleanup(1)

.BR mu-find(1)

.BR mu-mkdir(1)

.BR mu-view(1)

.BR mu-extract(1)
