.TH MUG 1 "November 2010" "User Manuals"

.SH NAME 

mug \- a graphical user interface for \fBmu\fR mail searches

.SH SYNOPSIS

.B mug [options]

.SH DESCRIPTION

\fBmug\fR is a program for doing e-mail searches, using the \fBmu\fR-backend
for the actual searches and a GTK+ user-interface. \fBmug\fR is considered
merely a toy-demonstration of the mu-framework, but can nevertheless be quite
useful.

If \fBmug\fR finds the \fIbookmarks\fR-file in the mu-home directory, the
bookmarks from this file will be shown in mug as a list of buttons in the left
toolbar.

.SH OPTIONS

.TP
\fB\-\-muhome\fR causes \fBmug\fR to use an alternative directory to read its
database and bookmarks and write its logs. By default, \fI~/.mu\fR is used.

.SH BUGS
Please report bugs if you find them:
.BR https://github.com/djcb/mu/issues

.SH AUTHOR

Dirk-Jan C. Binnema <djcb@djcbsoftware.nl>

.SH "SEE ALSO"

.BR mu(1) mu-bookmarks(5)
