#+STARTUP:showall
* IDEAS

Ideas for future enhancements. We collect those here so they don't clutter up
the Github issue list, i.e. without any clear plan for adding in the near
future.

- Support automatic handling for List-Unsubscribe headers and more in general,
  handle mailing-list commands https://github.com/djcb/mu/issues/2623 and
  https://github.com/djcb/mu/issues/2724 This seems useful, but probably
  requires a lot of testing to get right. Can we re-use the Gnus code for this?

- Allow for *muting* messages https://github.com/djcb/mu/issues/636 Useful;
  probably need to do this by *remembering* the thread-id of muted messages; and
  management (unmute etc.). Perhaps at the mu side, a list of thread-id to add
  to each query for what *not* to match.

- Support *creating* calendar invitations.
  https://github.com/djcb/mu/issues/2308
  Shouldn't be _too_ hard, for someone that uses the functionality.

- Include "message summary" in message information, for display in the headers
  buffer: https://github.com/djcb/mu/issues/1821 It's not so easy to get a
  useful one line description... perhaps the first line after the "Dear x,"?
  Moreover, this requires new functionality on the headers-view side as well.

- Support indexing PDF (and other) attachments. This can be done extending
  process_message_part in mu-message.cc; instead of using something
  PDF-specific, we could pipe a PDF through some tool to extract text; and we'd
  need some way for users to specify a MIME-type => tool mapping  (in Config).
  https://github.com/djcb/mu/issues/2117

- Support "aggregate actions" apply to a set of messages, e.g. apply patch-set
  in a set of messages. That'll require some advanced scripting, maybe using
  Guile.
  https://github.com/djcb/mu/issues/301
  https://github.com/djcb/mu/issues/2704

- Try to guess the encodings; sometimes people send messages that e.g., claim
  they are ISO-8859-1 but actually use windows-1252, resulting in some
  characters being shown incorrectly. Perhaps best solved by GMime, but maybe mu
  can do something. https://github.com/djcb/mu/issues/2700

- Revamp the Guile support; mu has support Guile scripting for a long time, but
  it's gone a bit stale, and the API is not very nice. It'd be nice to revamp
  this support, so it becomes more widely useful.
  https://github.com/djcb/mu/issues/1982

- Display the messages from old-to-new (still get the newest though)
  https://github.com/djcb/mu/issues/2759

- Make sorting stable if there are multiple messages with the same date. We
  _could_ do this by adding some random millisecs to each messasge's timestamp; _or_
  complicating the search (i.e., the message hash?). Maybe leave as is?
  https://github.com/djcb/mu/issues/2527


- Perhaps better support file names with commas.. perhaps temporarily add some
  invisible unicode to fool crm-separator?
  https://github.com/djcb/mu/issues/2768

* Done

- Support mu4e-mark-handle-when also for when leaving emacs
  (kill-emacs-query-functions).
  https://github.com/djcb/mu/issues/2649
