#+TITLE:MU
[[https://github.com/djcb/mu/blob/master/COPYING][https://img.shields.io/github/license/djcb/mu?logo=gnu&.svg]]
[[https://en.cppreference.com][https://img.shields.io/badge/Made%20with-C/CPP-1f425f?logo=c&.svg]]
[[https://img.shields.io/github/v/release/djcb/mu][https://img.shields.io/github/v/release/djcb/mu.svg]]
[[https://github.com/djcb/mu/graphs/contributors][https://img.shields.io/github/contributors/djcb/mu.svg]]
[[https://github.com/djcb/mu/issues][https://img.shields.io/github/issues/djcb/mu.svg]]
[[https://github.com/djcb/mu/issues?q=is%3Aissue+is%3Aopen+label%3Arfe][https://img.shields.io/github/issues/djcb/mu/rfe?color=008b8b.svg]]
[[https://github.com/djcb/mu/pull/new][https://img.shields.io/badge/PRs-welcome-brightgreen.svg]]\\
[[https://melpa.org/#/?q=mu4e&sort=version&asc=false][https://img.shields.io/badge/Emacs-25.3-922793?logo=gnu-emacs&logoColor=b39ddb&.svg]]
[[https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#Dependencies-for-Debian_002fUbuntu][https://img.shields.io/badge/Platform-Linux-2e8b57?logo=linux&.svg]]
[[https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html#Building-from-a-release-tarball-1][https://img.shields.io/badge/Platform-FreeBSD-8b3a3a?logo=freebsd&logoColor=c32136&.svg]]
[[https://formulae.brew.sh/formula/mu#default][https://img.shields.io/badge/Platform-macOS-101010?logo=apple&logoColor=ffffff&.svg]]
[[https://github.com/msys2-unofficial/MSYS2-packages/blob/master/mu/README.org][https://img.shields.io/badge/Platform-Windows-00bfff?logo=windows&logoColor=00bfff&.svg]]

Welcome to ~mu~!

*Note*: you are looking at the *development* branch, which is where new
code is being developed and tested, and which may occasionally break.

Distribution and non-adventurous users are instead recommended to use
the [[https://github.com/djcb/mu/tree/release/1.6.x][1.6.x Release Branch]] or to pick up one of the [[https://github.com/djcb/mu/releases][1.4.x Releases]].

Given the enormous amounts of e-mail many people gather and the
importance of e-mail message in our work-flows, it's essential to
quickly deal with all that mail - in particular, to instantly find
that one important e-mail you need right now, and quickly file away
message for later use.

~mu~ is a tool for dealing with e-mail messages stored in the
Maildir-format. ~mu~'s purpose in life is to help you to quickly find
the messages you need; in addition, it allows you to view messages,
extract attachments, create new maildirs, and so on. See the [[www/cheatsheet.md][mu
cheatsheet]] for some examples. =mu= is fully documented.

After indexing your messages into a [[http://www.xapian.org][Xapian]]-database, you can search
them using a custom query language. You can use various message fields
or words in the body text to find the right messages.

Built on top of ~mu~ are some extensions (included in this package):

- mu4e: a full-featured e-mail client that runs inside emacs

- mu-guile: bindings for the Guile/Scheme programming language (version 2.2 and later)

~mu~ is written in C and C++; ~mu4e~ is written in elisp, and ~mu-guile~ in
a mix of C and Scheme.

Note, ~mu~ is available in Linux distributions (e.g. Debian/Ubuntu and
Fedora) under the name ~maildir-utils~; apparently because they don't
like short names. The all of the code is distributed under the terms
of the [[https://www.gnu.org/licenses/gpl-3.0.en.html][GNU General Public License version 3]] (or higher).
