* Welcome to mu!

  Given the enormous amounts of e-mail many people gather and the importance of
  e-mail message in our work-flows, it's essential to quickly deal with all that
  mail - in particular, to instantly find that one important e-mail you need right
  now.
  
  [[http://www.djcbsoftware.nl/code/mu][mu]] is a tool for dealing with e-mail messages stored in the
  Maildir-format. =mu='s purpose in life is to help you to quickly find the
  messages you need; in addition, it allows you to view messages, extract
  attachments, create new maildirs, and so on. See the [[http://www.djcbsoftware.nl/code/mu/cheatsheet.html][mu cheatsheet]] for some
  examples. =mu= is fully documented.
  
  After indexing your messages into a [[http://www.xapian.org][Xapian]]-database, you can search them using
  a custom query language. You can use various message fields or words in the
  body text to find the right messages.
  
  Built on top of the mu, are some extensions (included in this package):

  - mu-for-emacs ([[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]]): a full-featured e-mail client that runs inside emacs
  - [[http://www.djcbsoftware.nl/code/mu/mu-guile.html][mu-guile]]: bindings for the Guile/Scheme programming language (version 2.0
    and later)
  - a toy GTK+-interface called 'mug' (in the 'toys/' subdir)

  =mu= is written in C and a bit of C++ (to interface with Xapian), with =mu4e=
  written in [[http://en.wikipedia.org/wiki/Emacs-Lisp][Emacs-Lisp]] and =mu-guile= in a mix of C and Scheme.
  
  Note, =mu= is available in Debian/Ubuntu under the name =maildir-utils=;
  apparently because they don't like short name. It's also possible to confuse
  that name with the [[http://mailutils.org/][GNU Mailutils]] project (which is totally unrelated) - but
  now you have been warned.
  
