* Welcome to mu!


  Given the enormous amounts of e-mail many people gather and the importance of
  e-mail message in our work-flows, it's essential to quickly deal with all that
  mail - in particular, to instantly find that one important e-mail you need right
  now.
  
  [[http://www.djcbsoftware.nl/code/mu][mu]] is a tool for dealing with e-mail messages stored in the
  Maildir-format. mu's main purpose is to help you to quickly find the messages
  you need; in addition, it allows you to view messages, extract attachments,
  create new maildirs, and so on. See the [[http://www.djcbsoftware.nl/code/mu/cheatsheet.html][mu cheatsheet]] for some examples.
  
  Searching works by first indexing your messages into a Xapian-database, which
  can then be queried using a custom query language.
  
  Built on top of the mu, are some extensions (included in this package):

  * mu-for-emacs ([[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]]): a full-featured e-mail client that runs inside emacs
  * [[http://www.djcbsoftware.nl/code/mu/mu-guile.html][mu-guile]]: bindings for the Guile/Scheme programming language

  And, there is a toy GTK+-interface called 'mug' (in the 'toys/' subdir)

  Mu is written in C and a bit of C++, with mu4e written in Emacs-Lisp and
  mu-guile in a mix of C and Scheme.
  
  Note, mu is available in Debian/Ubuntu under the name =maildir-utils=,
  apparently because they don't like short name. It's also possible to confuse
  that name with the [[http://mailutils.org/][GNU Mailutils]] project (which is totally unrelated) - but
  now you have been warned.
  
