# fish completion for mu; generated by 'mu completions fish' (mu 1.14.4); do not edit.

complete -c mu -s V -l version -d 'Display program version information and exit'
complete -c mu -s h -l help -d 'Show help information'
complete -c mu -l help-all -d 'Show help for all commands'
complete -c mu -s q -l quiet -d 'Hide non-essential output'
complete -c mu -s v -l verbose -d 'Show verbose output'
complete -c mu -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_use_subcommand" -f -a add -d 'Add messages to the database'
complete -c mu -n "__fish_use_subcommand" -f -a cfind -d 'Find contacts matching some pattern'
complete -c mu -n "__fish_use_subcommand" -f -a extract -d 'Extract attachments and other MIME-parts'
complete -c mu -n "__fish_use_subcommand" -f -a fields -d 'Superseded by \'mu info\''
complete -c mu -n "__fish_use_subcommand" -f -a find -d 'Find messages matching some query'
complete -c mu -n "__fish_use_subcommand" -f -a help -d 'Show help information'
complete -c mu -n "__fish_use_subcommand" -f -a index -d 'Scan maildirs and store information'
complete -c mu -n "__fish_use_subcommand" -f -a info -d 'Show information about mu'
complete -c mu -n "__fish_use_subcommand" -f -a init -d 'Initialize the mu database'
complete -c mu -n "__fish_use_subcommand" -f -a labels -d 'Manage message labels'
complete -c mu -n "__fish_use_subcommand" -f -a mkdir -d 'Create a new Maildir'
complete -c mu -n "__fish_use_subcommand" -f -a move -d 'Move a message or change its flags'
complete -c mu -n "__fish_use_subcommand" -f -a remove -d 'Remove message from file-system and database'
complete -c mu -n "__fish_use_subcommand" -f -a scm -d 'Start Guile/Scheme shell or run script'
complete -c mu -n "__fish_use_subcommand" -f -a server -d 'Start a mu server (for mu4e)'
complete -c mu -n "__fish_use_subcommand" -f -a verify -d 'Verify cryptographic signatures'
complete -c mu -n "__fish_use_subcommand" -f -a view -d 'View specific messages'

# mu add
complete -c mu -n "__fish_seen_subcommand_from add" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from add" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from add" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from add" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from add" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from add" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from add" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from add" -F

# mu cfind
complete -c mu -n "__fish_seen_subcommand_from cfind" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from cfind" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from cfind" -s o -l format -x -a 'bbdb csv json mutt-ab mutt-alias org-contact plain wl' -d 'Output format'
complete -c mu -n "__fish_seen_subcommand_from cfind" -s p -l personal -d 'Only show \'personal\' contacts'
complete -c mu -n "__fish_seen_subcommand_from cfind" -l after -x -d 'Only show results after some timestamps'
complete -c mu -n "__fish_seen_subcommand_from cfind" -s n -l maxnum -x -d 'Maximum number of results'
complete -c mu -n "__fish_seen_subcommand_from cfind" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from cfind" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from cfind" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from cfind" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from cfind" -l nocolor -d 'Don\'t show ANSI colors'

# mu extract
complete -c mu -n "__fish_seen_subcommand_from extract" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from extract" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from extract" -s r -l auto-retrieve -d 'Attempt to automatically retrieve online keys'
complete -c mu -n "__fish_seen_subcommand_from extract" -l decrypt -d 'Attempt to decrypt'
complete -c mu -n "__fish_seen_subcommand_from extract" -s a -l save-attachments -d 'Save all attachments'
complete -c mu -n "__fish_seen_subcommand_from extract" -l save-all -d 'Save all MIME parts'
complete -c mu -n "__fish_seen_subcommand_from extract" -l overwrite -d 'Overwrite existing files'
complete -c mu -n "__fish_seen_subcommand_from extract" -l play -d 'Attempt to open the extracted parts'
complete -c mu -n "__fish_seen_subcommand_from extract" -l parts -x -d 'Save specific parts (comma-sep\'d list)'
complete -c mu -n "__fish_seen_subcommand_from extract" -l target-dir -x -a "(__fish_complete_directories)" -d 'Target directory for saving'
complete -c mu -n "__fish_seen_subcommand_from extract" -s u -l uncooked -d 'Avoid massaging extracted file-names'
complete -c mu -n "__fish_seen_subcommand_from extract" -l matches -x -d 'Regular expression for files to save'
complete -c mu -n "__fish_seen_subcommand_from extract" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from extract" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from extract" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from extract" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from extract" -F

# mu fields
complete -c mu -n "__fish_seen_subcommand_from fields" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from fields" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from fields" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from fields" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from fields" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from fields" -l nocolor -d 'Don\'t show ANSI colors'

# mu find
complete -c mu -n "__fish_seen_subcommand_from find" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from find" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from find" -s t -l threads -d 'Show message threads'
complete -c mu -n "__fish_seen_subcommand_from find" -s u -l skip-dups -d 'Show only one of messages with same message-id'
complete -c mu -n "__fish_seen_subcommand_from find" -s r -l include-related -d 'Include related messages in results'
complete -c mu -n "__fish_seen_subcommand_from find" -s a -l analyze -d 'Analyze the query'
complete -c mu -n "__fish_seen_subcommand_from find" -s o -l format -x -a 'json json2 links plain sexp xml' -d 'Output format'
complete -c mu -n "__fish_seen_subcommand_from find" -s n -l maxnum -x -d 'Maximum number of results'
complete -c mu -n "__fish_seen_subcommand_from find" -s f -l fields -x -d 'Fields to display'
complete -c mu -n "__fish_seen_subcommand_from find" -s s -l sortfield -x -a 'a bcc c cc changed d date f flags from g h i k l labels language list m maildir message-id p path priority q r references s size subject t tags thread to u utc-offset v w x z' -d 'Field to sort the results by'
complete -c mu -n "__fish_seen_subcommand_from find" -s z -l reverse -d 'Sort in descending order'
complete -c mu -n "__fish_seen_subcommand_from find" -s b -l bookmark -x -d 'Use bookmarked query'
complete -c mu -n "__fish_seen_subcommand_from find" -l clearlinks -d 'Clear old links first'
complete -c mu -n "__fish_seen_subcommand_from find" -l linksdir -x -a "(__fish_complete_directories)" -d 'Target directory for symlinks'
complete -c mu -n "__fish_seen_subcommand_from find" -l after -x -d 'Only show messages whose message file was changed after some timestamp'
complete -c mu -n "__fish_seen_subcommand_from find" -l summary-len -x -d 'Use up to so many lines for the summary'
complete -c mu -n "__fish_seen_subcommand_from find" -l exec -x -d 'Command to execute on message file'
complete -c mu -n "__fish_seen_subcommand_from find" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from find" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from find" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from find" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from find" -l nocolor -d 'Don\'t show ANSI colors'

# mu help
complete -c mu -n "__fish_seen_subcommand_from help" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from help" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from help" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from help" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from help" -l nocolor -d 'Don\'t show ANSI colors'

# mu index
complete -c mu -n "__fish_seen_subcommand_from index" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from index" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from index" -l lazy-check -d 'Skip based on dir-timestamps'
complete -c mu -n "__fish_seen_subcommand_from index" -l nocleanup -d 'Don\'t clean up database after indexing'
complete -c mu -n "__fish_seen_subcommand_from index" -l reindex -d 'Perform a complete reindexing'
complete -c mu -n "__fish_seen_subcommand_from index" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from index" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from index" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from index" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from index" -l nocolor -d 'Don\'t show ANSI colors'

# mu info
complete -c mu -n "__fish_seen_subcommand_from info" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from info" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from info" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from info" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from info" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from info" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from info" -l nocolor -d 'Don\'t show ANSI colors'

# mu init
complete -c mu -n "__fish_seen_subcommand_from init" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from init" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from init" -s m -l maildir -x -a "(__fish_complete_directories)" -d 'Root maildir'
complete -c mu -n "__fish_seen_subcommand_from init" -l personal-address -l my-address -x -d 'Personal e-mail address or regexp (can be used multiple times)'
complete -c mu -n "__fish_seen_subcommand_from init" -l ignored-address -x -d 'Ignored e-mail address or regexp'
complete -c mu -n "__fish_seen_subcommand_from init" -l max-message-size -x -d 'Maximum allowed message size in bytes'
complete -c mu -n "__fish_seen_subcommand_from init" -l batch-size -x -d 'Maximum size of database transaction'
complete -c mu -n "__fish_seen_subcommand_from init" -l support-ngrams -d 'Support CJK n-grams for querying/indexing'
complete -c mu -n "__fish_seen_subcommand_from init" -l reinit -d 'Re-initialize database with current settings'
complete -c mu -n "__fish_seen_subcommand_from init" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from init" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from init" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from init" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from init" -l nocolor -d 'Don\'t show ANSI colors'

# mu labels
complete -c mu -n "__fish_seen_subcommand_from labels" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from labels" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from labels" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from labels" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from labels; and not __fish_seen_subcommand_from update clear list restore-list export import" -f -a update -d 'update labels'
complete -c mu -n "__fish_seen_subcommand_from labels; and not __fish_seen_subcommand_from update clear list restore-list export import" -f -a clear -d 'clear all labels from matched messages'
complete -c mu -n "__fish_seen_subcommand_from labels; and not __fish_seen_subcommand_from update clear list restore-list export import" -f -a list -d 'list labels in the store'
complete -c mu -n "__fish_seen_subcommand_from labels; and not __fish_seen_subcommand_from update clear list restore-list export import" -f -a restore-list -d 'restore the labels cache'
complete -c mu -n "__fish_seen_subcommand_from labels; and not __fish_seen_subcommand_from update clear list restore-list export import" -f -a export -d 'export labels to a file'
complete -c mu -n "__fish_seen_subcommand_from labels; and not __fish_seen_subcommand_from update clear list restore-list export import" -f -a import -d 'import labels from a file'

# mu update
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from update" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from update" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from update" -l labels -x -d 'One or more comma-separated +label,-label'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from update" -s n -l dry-run -d 'Output what would change without changing anything'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from update" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'

# mu clear
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from clear" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from clear" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from clear" -s n -l dry-run -d 'Output what would change without changing anything'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from clear" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'

# mu list
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from list" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from list" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from list" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'

# mu restore-list
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from restore-list" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from restore-list" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from restore-list" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'

# mu export
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from export" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from export" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from export" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from export" -F

# mu import
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from import" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from import" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from import" -s n -l dry-run -d 'Output what would change without changing anything'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from import" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from labels; and __fish_seen_subcommand_from import" -F

# mu mkdir
complete -c mu -n "__fish_seen_subcommand_from mkdir" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -l mode -x -d 'Set the access mode (octal)'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from mkdir" -f -a "(__fish_complete_directories)"

# mu move
complete -c mu -n "__fish_seen_subcommand_from move" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from move" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from move" -l change-name -d 'Change name of target file'
complete -c mu -n "__fish_seen_subcommand_from move" -l update-dups -d 'Update duplicate messages too'
complete -c mu -n "__fish_seen_subcommand_from move" -s n -l dry-run -d 'Print target name, but do not change anything'
complete -c mu -n "__fish_seen_subcommand_from move" -l flags -x -d 'Target flags'
complete -c mu -n "__fish_seen_subcommand_from move" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from move" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from move" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from move" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from move" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from move" -F

# mu remove
complete -c mu -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from remove" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from remove" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from remove" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from remove" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from remove" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from remove" -F

# mu scm
complete -c mu -n "__fish_seen_subcommand_from scm" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from scm" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from scm" -l listen -d 'Start SCM REPL on a domain socket'
complete -c mu -n "__fish_seen_subcommand_from scm" -l eval -x -d 'Expression to evaluate'
complete -c mu -n "__fish_seen_subcommand_from scm" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from scm" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from scm" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from scm" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from scm" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from scm" -F

# mu server
complete -c mu -n "__fish_seen_subcommand_from server" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from server" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from server" -l commands -d 'List available commands'
complete -c mu -n "__fish_seen_subcommand_from server" -l eval -x -d 'Evaluate mu server expression'
complete -c mu -n "__fish_seen_subcommand_from server" -l allow-temp-file -d 'Allow for the temp-file optimization'
complete -c mu -n "__fish_seen_subcommand_from server" -l listen -d 'Start SCM REPL on a domain socket'
complete -c mu -n "__fish_seen_subcommand_from server" -l muhome -x -a "(__fish_complete_directories)" -d 'Specify alternative mu directory'
complete -c mu -n "__fish_seen_subcommand_from server" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from server" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from server" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from server" -l nocolor -d 'Don\'t show ANSI colors'

# mu verify
complete -c mu -n "__fish_seen_subcommand_from verify" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from verify" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from verify" -s r -l auto-retrieve -d 'Attempt to automatically retrieve online keys'
complete -c mu -n "__fish_seen_subcommand_from verify" -l decrypt -d 'Attempt to decrypt'
complete -c mu -n "__fish_seen_subcommand_from verify" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from verify" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from verify" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from verify" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from verify" -F

# mu view
complete -c mu -n "__fish_seen_subcommand_from view" -s h -l help -d 'Show help information'
complete -c mu -n "__fish_seen_subcommand_from view" -l help-all -d 'Show help for all commands'
complete -c mu -n "__fish_seen_subcommand_from view" -s o -l format -x -a 'html plain sexp' -d 'Output format'
complete -c mu -n "__fish_seen_subcommand_from view" -s r -l auto-retrieve -d 'Attempt to automatically retrieve online keys'
complete -c mu -n "__fish_seen_subcommand_from view" -l decrypt -d 'Attempt to decrypt'
complete -c mu -n "__fish_seen_subcommand_from view" -l summary-len -x -d 'Use up to so many lines for the summary'
complete -c mu -n "__fish_seen_subcommand_from view" -l terminate -d 'Insert form-feed after each message'
complete -c mu -n "__fish_seen_subcommand_from view" -s V -l version -d 'Display program version information and exit'
complete -c mu -n "__fish_seen_subcommand_from view" -s q -l quiet -d 'Hide non-essential output'
complete -c mu -n "__fish_seen_subcommand_from view" -s v -l verbose -d 'Show verbose output'
complete -c mu -n "__fish_seen_subcommand_from view" -l nocolor -d 'Don\'t show ANSI colors'
complete -c mu -n "__fish_seen_subcommand_from view" -F
